
// This file is auto-generated by remote notification script
// Last updated: 2026-06-08T12:24:30.259Z

export const REMOTE_NOTIFICATION = {
  "id": "1780921470256",
  "title": "🎁 Surprise!",
  "body": "Check the app - I left you something special! 🎁",
  "type": "surprise",
  "cooldown": 3600000,
  "sound": true,
  "data": {},
  "createdAt": "2026-06-08T12:24:30.256Z"
};

export function shouldShowNotification() {
  const lastShown = localStorage.getItem('last_notification_shown');
  const now = Date.now();
  
  // Don't show if shown in last 3600000ms
  if (lastShown && now - parseInt(lastShown) < 3600000) {
    return false;
  }
  
  localStorage.setItem('last_notification_shown', now.toString());
  return true;
}
