# fly.toml app configuration file generated for nova-calls on 2026-07-05T09:08:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


app = "nova-calls"
primary_region = "fra"

[build]
  image = "livekit/livekit-server:latest"

[env]
  LIVEKIT_API_KEY = "APIfeK4aTdAcL3PrvHZOQfZ"
  LIVEKIT_API_SECRET = " secret7xtxHDr6Xl7pqmcxQMZ7M90AebHEuO96JLw8xd3p"
  LIVEKIT_KEYS = "APIfeK4aTdAcL3PrvHZOQfZ:  secret7xtxHDr6Xl7pqmcxQMZ7M90AebHEuO96JLw8xd3p"

[[services]]
  internal_port = 7880
  protocol = "tcp"

  [[services.ports]]
    port = 7880

  [[services.ports]]
    port = 443
    handlers = ["tls"]
    [services.ports.tls]
      ports = ["7880"]

  [[services.ports]]
    port = 7881
    handlers = ["tls"]
    [services.ports.tls]
      ports = ["7881"]

  [[services.ports]]
    port = 7882
