// scripts/sendRemoteNotification.js
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

// Configuration
const NOTIFICATION_TYPES = {
  LOVE_MESSAGE: 'love_message',
  MEMORY_REMINDER: 'memory_reminder',
  MOOD_CHECK: 'mood_check',
  SURPRISE: 'surprise',
  CUSTOM: 'custom'
};

class RemoteNotificationSender {
  constructor(projectDir) {
    this.projectDir = projectDir;
  }

  // Create a notification update file
  createNotificationUpdate(notification) {
    const updateContent = `
// This file is auto-generated by remote notification script
// Last updated: ${new Date().toISOString()}

export const REMOTE_NOTIFICATION = ${JSON.stringify(notification, null, 2)};

export function shouldShowNotification() {
  const lastShown = localStorage.getItem('last_notification_shown');
  const now = Date.now();
  
  // Don't show if shown in last ${notification.cooldown || 3600000}ms
  if (lastShown && now - parseInt(lastShown) < ${notification.cooldown || 3600000}) {
    return false;
  }
  
  localStorage.setItem('last_notification_shown', now.toString());
  return true;
}
`;

    const filePath = path.join(this.projectDir, 'constants', 'RemoteNotification.ts');
    fs.writeFileSync(filePath, updateContent);
    console.log(`✅ Notification update created at: ${filePath}`);
    return filePath;
  }

  // Build and publish update
  async publishUpdate(message, options = {}) {
    const notification = {
      id: Date.now().toString(),
      title: options.title || '💕 Love Note',
      body: message,
      type: options.type || NOTIFICATION_TYPES.LOVE_MESSAGE,
      cooldown: options.cooldown || 3600000, // 1 hour default
      sound: true,
      data: options.data || {},
      createdAt: new Date().toISOString()
    };

    // Create the update file
    this.createNotificationUpdate(notification);

    // Build and publish
    console.log('📦 Building and publishing OTA update...');
    
    exec('EAS_SKIP_AUTO_FINGERPRINT=1 CI=1 eas update --branch production --message "updated notification"', 
      { cwd: this.projectDir },
      (error, stdout, stderr) => {
        if (error) {
          console.error('❌ Failed to publish:', error);
          return;
        }
        console.log('✅ OTA Update published!');
        console.log('📱 The app will show the notification on next load');
        console.log(`💬 Message: "${message}"`);
      }
    );
  }

  // Send a love message
  async sendLoveMessage(message, options = {}) {
    await this.publishUpdate(message, {
      title: '💕 Thinking of You',
      type: NOTIFICATION_TYPES.LOVE_MESSAGE,
      ...options
    });
  }

  // Send a memory reminder
  async sendMemoryReminder(memoryTitle, options = {}) {
    await this.publishUpdate(`Remember when we had ${memoryTitle}? 💭`, {
      title: '📸 Memory Reminder',
      type: NOTIFICATION_TYPES.MEMORY_REMINDER,
      ...options
    });
  }

  // Send a surprise notification
  async sendSurprise(message, options = {}) {
    await this.publishUpdate(message, {
      title: '🎁 Surprise!',
      type: NOTIFICATION_TYPES.SURPRISE,
      ...options
    });
  }
}

// CLI Usage
if (require.main === module) {
  const args = process.argv.slice(2);
  const command = args[0];
  const message = args[1];
  
  const sender = new RemoteNotificationSender(process.cwd());
  
  switch(command) {
    case 'love':
      sender.sendLoveMessage(message || 'Just thinking about you! 💕');
      break;
    case 'memory':
      sender.sendMemoryReminder(message || 'that special moment');
      break;
    case 'surprise':
      sender.sendSurprise(message || 'Something special is waiting for you! 🎁');
      break;
    default:
      console.log(`
Usage:
  node sendNotification.js love "Your message here"
  node sendNotification.js memory "our first date"
  node sendNotification.js surprise "Check the app for a surprise!"
      `);
  }
}

module.exports = RemoteNotificationSender;
